# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: my_standart
    configs:
        my_standart:
            toolbar: "my_standart"
    toolbars:
        configs:
            my_standart: [["Source", "-", "Bold", "Italic", "Link", "Unlink", "Anchor", "Table", "NumberedList", "BulletedList", "-", "TextColor", "BGColor", "-", "RemoveFormat", "-", 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']]
