security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: entity_user_provider
            guard:
                authenticators:
                    - App\Components\Security\Authenticator\LoginFormAuthenticator
                entry_point: App\Components\Security\Authenticator\LoginFormAuthenticator
            logout:
                path: logout

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
