app_controllers:
    resource: ../../src/Components/Balticrest/Controller/
    type: annotation
    prefix:
        ru: ''
        en: '/en'
        de: '/de'
        pl: '/pl'
        lt: '/lt'
        cn: '/cn'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
