worker_processes  1;

events {
    worker_connections 1024;
}

http {
    include            mime.types;
    default_type       application/octet-stream;
    sendfile           on;
    keepalive_timeout  65;

    server {

        listen 80;

        charset utf-8;

        client_max_body_size 50M;

        access_log  /var/log/nginx/balticrest_access.log combined;
        error_log   /var/log/nginx/balticrest_error.log;

        root /var/www/balticrest.ru/public;

        index index.php;

        location / {
	        try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.(eot|svg|ttf|woff|txt|jpeg|jpg|gif|png|ico|css|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|tar|wav|bmp|rtf|js|djvu|mht|chm|swf|avi|xml|ogg|mp3)$ {
	        try_files $uri =404;
        }

        location ~ \.php$ {
            fastcgi_pass php-fpm:9000;
            fastcgi_index  index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}