monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            excluded_http_codes: [404]
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: email_log
        email_log:
            type: symfony_mailer
            from_email: '%env(MAILER_FROM)%'
            to_email: '%env(ADMIN_EMAIL)%'
            subject: 'Ошибка на сайте balticrest.ru'
            level: debug
            formatter:  monolog.formatter.html
            content_type: text/html
        file_log:
            level: error
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 10
