# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.mailer.from: '%env(MAILER_FROM)%'
    app.vk.client_id: '%env(VKONTAKTE_CLIENT_ID)%'
    app.vk.client_secret: '%env(VKONTAKTE_CLIENT_SECRET)%'
    app.fb.app_id: '%env(FACEBOOK_APP_ID)%'
    app.fb.app_secret: '%env(FACEBOOK_APP_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

imports:
    - { resource: '../src/Components/Admin/config/services.yaml'}
    - { resource: '../src/Components/Balticrest/config/services.yaml'}