[supervisord]
nodaemon=true
user=root

[program:consumer]
command=php /var/www/balticrest.ru/bin/console messenger:consume async -vv
stdout_logfile=/var/log/supervisor/consumer.log
stderr_logfile=/var/log/supervisor/consumer.error.log
